<a href="https://colab.research.google.com/github/sokhan1/Introduction-to-data-analysts/blob/main/3_05_filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Filtering


*   Filtering in pd.DataFrame is the process of leaving only rows that meet a condition

In [ ]:
import pandas as pd
data = {
    'Name':['A','B','C','D'],
    'Age':[25,30,35,40],
    'City':['New York','Los Angeles','New York', 'Chicago']
}

df = pd.DataFrame(data)

In [ ]:
df

  Name  Age         City
0    A   25     New York
1    B   30  Los Angeles
2    C   35     New York
3    D   40      Chicago

In [ ]:
con = df.Age>30
df['age_over_30'] = con
df

  Name  Age         City  age_over_30
0    A   25     New York        False
1    B   30  Los Angeles        False
2    C   35     New York         True
3    D   40      Chicago         True

In [ ]:
df[con]

  Name  Age      City  age_over_30
2    C   35  New York         True
3    D   40   Chicago         True

In [ ]:
df[df.Age>30]

  Name  Age      City  age_over_30
2    C   35  New York         True
3    D   40   Chicago         True

#between(), isin(), isna()

In [ ]:
import seaborn as sns
df = sns.load_dataset('titanic')

In [ ]:
df.head() #20 years old or older 22 years old or younger # between(20,22)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
con = df.age.between(20,22) #method

In [ ]:
df[con].age.value_counts()

age
22.0    27
21.0    24
20.0    15
20.5     1
Name: count, dtype: int64

In [ ]:
df.embarked.value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [ ]:
con2 = df.embarked.isin(['S','C'])
df[con2].embarked.value_counts()

embarked
S    644
C    168
Name: count, dtype: int64

In [ ]:
# isna only loads things with no value
df.head() #deck

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.deck.value_counts() # From this sentence, We can not see Nan

deck
C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: count, dtype: int64

In [ ]:
df.deck.value_counts(dropna = False)

deck
NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: count, dtype: int64

In [ ]:
con3 =df.deck.isna()
df[con3]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df[~con3] #~=not

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

#and(&), or(|)


*   Combine two or more conditions

In [ ]:
True and False

False

In [ ]:
True or False

True

In [ ]:
True & False

False

In [ ]:
True | False

True

In [ ]:
df=pd.DataFrame({'num':[1,2,3,4,5,6,7,8,9]})

In [ ]:
df

   num
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9

In [ ]:
df['col_1']=df.num >= 6
df['col_2']=df.num >= 3
df['col_and']=df.col_1 & df.col_2
df['col_or']=df.col_1 | df.col_2
df

   num  col_1  col_2  col_and  col_or
0    1  False  False    False   False
1    2  False  False    False   False
2    3  False   True    False    True
3    4  False   True    False    True
4    5  False   True    False    True
5    6   True   True     True    True
6    7   True   True     True    True
7    8   True   True     True    True
8    9   True   True     True    True

#Exercise

1.   titanic dataset filtering
*   Filter data for passengers whose class is First and age is 30 or higher
*   Filter data for passengers with survived = 1 or embark_town = 'Southampton'
*   Filter data for passengers with fare > 100 and sex female

In [4]:
import seaborn as sns
df2=sns.load_dataset('titanic')

In [5]:
df2.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [12]:
filter1= (df2['class'] == 'First') #Parenthesize each of the conditions
filter1

0      False
1       True
2      False
3       True
4      False
       ...
886    False
887     True
888    False
889     True
890    False
Name: class, Length: 891, dtype: bool

In [14]:
filter1= (df2['class'] == 'First') & (df2.age >=30)
filter1

0      False
1       True
2      False
3       True
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [20]:
df2[filter1].age.value_counts().sort_index()

age
30.0    6
31.0    5
32.0    2
33.0    4
34.0    1
35.0    9
36.0    9
37.0    3
38.0    6
39.0    5
40.0    5
41.0    1
42.0    4
43.0    1
44.0    3
45.0    5
45.5    1
46.0    2
47.0    5
48.0    5
49.0    5
50.0    5
51.0    3
52.0    4
53.0    1
54.0    4
55.0    1
56.0    4
58.0    5
60.0    3
61.0    2
62.0    3
63.0    1
64.0    2
65.0    2
70.0    1
71.0    2
80.0    1
Name: count, dtype: int64

In [21]:
df2[filter1]['class'].value_counts().sort_index()

class
First     131
Second      0
Third       0
Name: count, dtype: int64

In [25]:
#Exercise 2
filter2 = (df2['survived']==1) | (df2['embark_town']=='Southampton')
filter2

0       True
1       True
2       True
3       True
4       True
       ...
886     True
887     True
888     True
889     True
890    False
Length: 891, dtype: bool

In [27]:
df2[filter2]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [31]:
df3=df2[filter2]
df3[df3['survived'] != 1].survived.value_counts()

survived
0    427
Name: count, dtype: int64

In [32]:
df3[df3['survived'] != 1].embark_town.value_counts()

embark_town
Southampton    427
Name: count, dtype: int64

In [34]:
filter3=(df2['fare']>=100) & (df2['sex']=='female')
filter3

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [37]:
df4=df2[filter3]
df4.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
88,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
195,1,1,female,58.0,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True
215,1,1,female,31.0,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True

In [39]:
df4[filter3].fare.value_counts()

<ipython-input-39-9f3b6b02dea1>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df4[filter3].fare.value_counts()

fare
211.3375    3
227.5250    3
151.5500    3
263.0000    2
120.0000    2
134.5000    2
164.8667    2
262.3750    2
146.5208    2
110.8833    2
135.6333    2
153.4625    2
113.2750    2
247.5208    1
133.6500    1
512.3292    1
106.4250    1
108.9000    1
Name: count, dtype: int64

In [41]:
df4[filter3]['sex'].value_counts()

<ipython-input-41-ae30c86c1629>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df4[filter3]['sex'].value_counts()

sex
female    34
Name: count, dtype: int64