<a href="https://colab.research.google.com/github/sokhan1/Introduction-to-data-analysts/blob/main/3_06_Dates_%26_Times_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# to_datatime


*   Convert time-related data to datetime objects in python
*   Can handle various types of date and time data



    *   pd.to_datetime(df['col'])

In [2]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/LectureNote1/taxis.csv')
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   object
 1   dropoff          6433 non-null   object
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: float64(5), int64(1), object(8)
memory usage: 703.7+ KB

In [7]:
df['pickup']=pd.to_datetime(df.pickup)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   object
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(1), object(7)
memory usage: 703.7+ KB

#to_period



*   Convert date/time data to a given period ('M','W','Y', etc.)

    *   df['col'].dt.to_period('period').dt.strftime(%Y-%m-%d)

In [9]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   object
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(1), object(7)
memory usage: 703.7+ KB

In [12]:
df.pickup.dt.to_period('W')

0       2019-03-18/2019-03-24
1       2019-03-04/2019-03-10
2       2019-03-25/2019-03-31
3       2019-03-04/2019-03-10
4       2019-03-25/2019-03-31
                ...
6428    2019-03-25/2019-03-31
6429    2019-03-25/2019-03-31
6430    2019-03-18/2019-03-24
6431    2019-03-04/2019-03-10
6432    2019-03-11/2019-03-17
Name: pickup, Length: 6433, dtype: period[W-SUN]

In [15]:
df['dropoff']=pd.to_datetime(df.dropoff)
df.dropoff.dt.to_period('W')

0       2019-03-18/2019-03-24
1       2019-03-04/2019-03-10
2       2019-03-25/2019-03-31
3       2019-03-04/2019-03-10
4       2019-03-25/2019-03-31
                ...
6428    2019-03-25/2019-03-31
6429    2019-03-25/2019-03-31
6430    2019-03-18/2019-03-24
6431    2019-03-04/2019-03-10
6432    2019-03-11/2019-03-17
Name: dropoff, Length: 6433, dtype: period[W-SUN]

In [17]:
df.pickup.dt.to_period('W').dt.strftime('%Y-%m-%d')

0       2019-03-24
1       2019-03-10
2       2019-03-31
3       2019-03-10
4       2019-03-31
           ...
6428    2019-03-31
6429    2019-03-31
6430    2019-03-24
6431    2019-03-10
6432    2019-03-17
Name: pickup, Length: 6433, dtype: object

In [18]:
df['pickup_w']=df.pickup.dt.to_period('W').dt.strftime('%Y-%m-%d')

In [19]:
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,pickup_w
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan,2019-03-24
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan,2019-03-10
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan,2019-03-31
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan,2019-03-10
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan,2019-03-31

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
 14  pickup_w         6433 non-null   object
dtypes: datetime64[ns](2), float64(5), int64(1), object(7)
memory usage: 754.0+ KB

##parse_dates



    *   read_csv( ,parse_dates = ['col1','col2'...])

In [23]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/LectureNote1/taxis.csv'
                ,parse_dates = ['pickup','dropoff']
                )
df.head(2)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 703.7+ KB

##timedelta


*   Used to indicate the difference between two dates or times


    *   df['duration'] = (df['end']-df['start']).dt.total_seconds()

In [25]:
df.dropoff - df.pickup

0      0 days 00:06:15
1      0 days 00:07:05
2      0 days 00:07:24
3      0 days 00:25:52
4      0 days 00:09:32
             ...
6428   0 days 00:03:34
6429   0 days 00:56:23
6430   0 days 00:19:07
6431   0 days 00:05:04
6432   0 days 00:16:40
Length: 6433, dtype: timedelta64[ns]

In [27]:
(df.dropoff - df.pickup).dt.total_seconds()/60

0        6.250000
1        7.083333
2        7.400000
3       25.866667
4        9.533333
          ...
6428     3.566667
6429    56.383333
6430    19.116667
6431     5.066667
6432    16.666667
Length: 6433, dtype: float64

In [28]:
df['minute_pickup_to_dropoff']=(df.dropoff - df.pickup).dt.total_seconds()/60

In [29]:
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,minute_pickup_to_dropoff
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan,6.250000
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan,7.083333
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan,7.400000
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan,25.866667
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan,9.533333